server:
  port: 8030
  
spring:
    application:
      name: project-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
      healthcheck:
        enable: true

#hystrix.command.default.execution.timeout.enabled: false

feign:
  hystrix:
    enable: true

logging:
  level:
    root: info
    org.yangbo: debug
